name: Focal
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0
  facebook_app_events: ^0.6.0
  provider: ^4.3.1
  font_awesome_flutter: ^8.8.1
  feather_icons_flutter: ^4.7.4
  intl: ^0.16.1
  fluttertoast: ^7.0.1
  flutter_dnd: ^0.1.2
  flutter_local_notifications: ^2.0.0+1
  url_launcher: ^5.5.0
  dots_indicator: ^1.2.0
  percent_indicator: ^2.1.5
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.8
  confetti: ^0.5.4
  charts_flutter:
    path: dependencies/charts/charts_flutter
  flutter_keyboard_visibility: ^3.2.2
  package_info: ^0.4.3
  launch_review: ^2.0.0
  share: ^0.6.5+4
  screenshot: ^0.2.0
  path_provider: ^1.6.24
  drag_and_drop_lists: ^0.2.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/qrcode/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Cabin-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Cabin-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Cabin-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Cabin-BoldItalic.ttf
          style: italic
          weight: 700
