name: vivi
description: vivi

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.4.0
  feather_icons_flutter: ^4.7.4
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  flutter_native_splash: ^1.2.0
  google_sign_in: ^4.5.9
  provider: ^4.3.2+3
  sign_in_with_apple: ^2.5.4
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Cabin-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Cabin-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Cabin-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Cabin-BoldItalic.ttf
          style: italic
          weight: 700

flutter_native_splash:
  image: assets/images/Logo Large Light.png
  color: "ffffff"
  android_disable_fullscreen: true
